name: ShvatkaUIBuild

on:
  push:
    branches: [ master, test ]
    tags: ["*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Prepare build metadata
        id: meta
        run: |
          echo "BUILD_AT=$(date -u +'%Y-%m-%dT%H:%M:%S%z')" >> "$GITHUB_OUTPUT"
          echo "VCS_HASH=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "COMMIT_AT=$(git show -s --format=%cI ${GITHUB_SHA})" >> "$GITHUB_OUTPUT"
          echo "VCS_NAME=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
      - uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: bomzheg/shvatka-ui
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          buildArgs: "BUILD_AT=${{ steps.meta.outputs.BUILD_AT }},VCS_HASH=${{ steps.meta.outputs.VCS_HASH }},VCS_NAME=${{ steps.meta.outputs.VCS_NAME }},COMMIT_AT=${{ steps.meta.outputs.COMMIT_AT }}"
