name: ShvatkaUIBuild

on:
  push:
    branches: [ master, web_app_auth ]
    tags: ["*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: |
          echo "BUILD_AT=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> "$GITHUB_OUTPUT"
          echo "VCS_SHA=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
      - uses: mr-smithers-excellent/docker-build-push@v6.2
        with:
          image: bomzheg/shvatka-ui
          addLatest: true
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          buildArgs: "BUILD_AT=${{steps.date.outputs.BUILD_AT}},VCS_SHA=${{steps.date.outputs.VCS_SHA}}"
